/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DynamicRouteRouteImport } from './routes/$dynamicRoute'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditPostIdRouteImport } from './routes/edit/$postId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DynamicRouteRoute = DynamicRouteRouteImport.update({
  id: '/$dynamicRoute',
  path: '/$dynamicRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditPostIdRoute = EditPostIdRouteImport.update({
  id: '/edit/$postId',
  path: '/edit/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$dynamicRoute': typeof DynamicRouteRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/edit/$postId': typeof EditPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$dynamicRoute': typeof DynamicRouteRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/edit/$postId': typeof EditPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$dynamicRoute': typeof DynamicRouteRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/edit/$postId': typeof EditPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$dynamicRoute'
    | '/about'
    | '/create'
    | '/signin'
    | '/signup'
    | '/edit/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$dynamicRoute'
    | '/about'
    | '/create'
    | '/signin'
    | '/signup'
    | '/edit/$postId'
  id:
    | '__root__'
    | '/'
    | '/$dynamicRoute'
    | '/about'
    | '/create'
    | '/signin'
    | '/signup'
    | '/edit/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DynamicRouteRoute: typeof DynamicRouteRoute
  AboutRoute: typeof AboutRoute
  CreateRoute: typeof CreateRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  EditPostIdRoute: typeof EditPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$dynamicRoute': {
      id: '/$dynamicRoute'
      path: '/$dynamicRoute'
      fullPath: '/$dynamicRoute'
      preLoaderRoute: typeof DynamicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$postId': {
      id: '/edit/$postId'
      path: '/edit/$postId'
      fullPath: '/edit/$postId'
      preLoaderRoute: typeof EditPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DynamicRouteRoute: DynamicRouteRoute,
  AboutRoute: AboutRoute,
  CreateRoute: CreateRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  EditPostIdRoute: EditPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
